using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace TrafikApi.Utility
{
    public class Json
    {
        public enum Environments { TrafficAnalyze, Python2_7, Python3_6 }
        public string CallPythonInCSharp(string filename, string arguments, Environments environment)
        {
            string result = "";
            try
            {
                ProcessStartInfo start = new ProcessStartInfo(); // Path to your Python environment

                start.Arguments = filename + " " + arguments; // First argument must be the Python script name, then afterwards each argument as a string
                start.UseShellExecute = false;// Do not use OS shell
                start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
                start.RedirectStandardError = true;
                start.CreateNoWindow = false;
                start.WorkingDirectory = @"C:\Program Files\PythonScripts\Scripts";
                switch (environment)
                {
                    case Environments.TrafficAnalyze:
                        start.FileName = @"E:\PythonScripts\envs\TrafficAnalyze\python.exe";
                        break;
                    case Environments.Python2_7:
                        start.FileName = @"E:\PythonScripts\envs\Python2_7\python.exe";
                        break;
                    case Environments.Python3_6:
                        start.FileName = @"E:\PythonScripts\envs\Python3_6\python.exe";
                        break;
                    default:
                        start.FileName = @"E:\PythonScripts\envs\Python3_6\python.exe";
                        break;
                }
                using (Process process = Process.Start(start))
                {
                    using (StreamReader reader = process.StandardOutput)
                    {
                        string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script

                        result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    }
                }
            }
            catch (Exception e)
            {
                System.IO.File.WriteAllText("Error.txt", e.Message);
            }
            return result;
        }
    }
}
